include:
  - board: seeeduino_xiao_ble
    shield: totem_dongle_C  prospector_adapter
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: totem_dongle_L rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: totem_dongle_R rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: settings_reset